# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
..- task

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj
  displayName:'Restore'Nuget package'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*csproj'
    arguments: '--no-restore'
  dispalyName:'Build project'
  condition: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Test.csproj'
  displayName: 'Run Test'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      project: '**/customerApi.csproj'
      arguments: '--configuration $(buidconfiguration) --no-restore'
      modifyoutpath: false
      dispalyName:'publish customer API'
