# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: DontNet-core-customerApi-CI
trigger:
.branch:
   include:
    - customerApi/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/customerApi*.csproj'
  displayName: 'Restore Nuge package'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/customerApi*.csproj'
    arguments: --no-restore'
    dispalyName: 'Build project'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/.Test.csproj'
    arguments: 'no-resore.--no-build'
  displayName: 'Run Test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/'customerApi*.csproj'
    arguments: '--configuration $(buildconfiguration) --no-restore'
    ModifyoutputPath: false 
  displayName: 'Publish CustomerApi'
